(:name           "haphic")
(:repo           "taffish-org/haphic")
(:author         "KaiyuanHan")
(:version        "1.0.6")
(:intro          "HapHiC: a fast, reference-independent, allele-aware scaffolding tool based on Hi-C data")
(:dependencies)
(:functions      "haphic")
